### ISSUE TITLE
Not trusted server certificate

### ISSUE THREAD

**Issue by Y2JChamp** [insanediv/SMP3.0ConnectionLib#1]
When i try to connect to a Https endpoint, the connectionLib raises the Following exception: javax.net.ssl.sslexception: Not trusted server Certificate

**Comment by insanediv** [comment]
Hi! Thank you for reporting this. You shoud specify the correct Ion instance when creating a SmpIntegration object. 
Please instantiate the object as follows
```java
IonFactory ionFactory = new IonFactory(context, TypeHttpProtocol.TYPE_HTTP_PROTOCOL_HTTPS);
Ion ion = ionFactory.build();
new SmpIntegration(context, ion, 'https://foo.smp.org', 'appid', true)
```
